Requests validations for chapter 1
meaboutsoftware/evolutionary-architecture pull request #139
Opened 2023-08-26 10:31 UTC by kamilbaczek

2023-08-26 10:32 UTC, kamilbaczek commented on Chapter-1-initial-architecture/Src/Fitnet.UnitTests/Contracts/PrepareContract/PrepareContractRequestValidatorTests.cs
> +    public void Given_PrepareContractRequest_With_Invalid_CustomerHeight_Should_Have_Validation_Error()
Adjust names to our tests names convention

2023-08-26 11:16 UTC, kamilbaczek commented on Chapter-1-initial-architecture/Src/Fitnet.UnitTests/Contracts/PrepareContract/PrepareContractRequestValidatorTests.cs
> +namespace EvolutionaryArchitecture.Fitnet.UnitTests.Contracts.PrepareContract;
Add to docs fluent validation and structor

2023-08-26 11:30 UTC, meaboutsoftware requested changes

2023-08-26 11:30 UTC, meaboutsoftware commented on Chapter-1-initial-architecture/Src/Fitnet/Common/Validation/Requests/RequestValidationsExtensions.cs
> +    internal static IServiceCollection AddRequestsValidations(this IServiceCollection services)
You do not need this extension, can use:

builder.Services.AddValidatorsFromAssemblyContaining<Program>();

Consider it :)

2023-08-26 11:30 UTC, meaboutsoftware commented on Chapter-1-initial-architecture/Src/Fitnet/Common/Validation/Requests/Logging/RequestValidationLogger.cs
> +internal sealed class RequestValidationLogger : IRequestValidationLogger
I would omit logging completely (as I do not think we want to introduce Serilog in our repo at the moment).

2023-08-26 11:30 UTC, meaboutsoftware commented on Chapter-1-initial-architecture/Src/Fitnet.UnitTests/Contracts/SignContract/SignContractRequestValidatorTests.cs
> +    public void Given_SignContractRequest_With_Invalid_SignedAt_Should_Have_Validation_Error()
Usually when I write tests for FluentValidation I try to handle all cases with Theory. E.g. if I have validation for NotEmpty, I put a test case that validates:

Null,
Empty,
Whitespace

Something like here:

```
internal static class XyzRequestValidatorTestsData
{
    private static readonly Faker Faker = new();

    public static IEnumerable<object[]> GetIncorrectText()
    {
        yield return new object[] { string.Empty };
        yield return new object[] { " " };
        yield return new object[] { "<script>alert('xss')</script>" };
        yield return new object[] { Faker.Random.String2(5001) };
    }
}
```

Then you have the usage as follows:

```
[Theory]
    [MemberData(nameof(XyztRequestValidatorTestsData.GetIncorrectText),
        MemberType = typeof(XyzRequestValidatorTestsData))]
```

2023-08-26 11:32 UTC, meaboutsoftware commented
I really like the way how you solved resolver

2023-08-26 14:29 UTC, kamilbaczek commented on Chapter-1-initial-architecture/Src/Fitnet/Common/Validation/Requests/RequestValidationsExtensions.cs
> +    internal static IServiceCollection AddRequestsValidations(this IServiceCollection services)
I  have looked for this extension method but I didn't found. I will use it

2023-08-26 14:32 UTC, kamilbaczek commented on Chapter-1-initial-architecture/Src/Fitnet.UnitTests/Contracts/SignContract/SignContractRequestValidatorTests.cs
> +    public void Given_SignContractRequest_With_Invalid_SignedAt_Should_Have_Validation_Error()
I know this approach. I used this way to have explicit named test cases but I am okay to do it in the way like you suggested.

2023-08-26 14:49 UTC, meaboutsoftware commented on Chapter-1-initial-architecture/Src/Fitnet.UnitTests/Contracts/SignContract/SignContractRequestValidatorTests.cs
> +    public void Given_SignContractRequest_With_Invalid_SignedAt_Should_Have_Validation_Error()
You can do it with separate test cases but handle all of them, not only default ;)

2023-08-27 13:35 UTC, meaboutsoftware approved these changes

2023-08-27 13:38 UTC, merged