Offer preparation
meaboutsoftware/evolutionary-architecture pull request #36
Opened 2023-05-02 20:58 UTC by kamilbaczek

2023-05-02 21:33 UTC, kamilbaczek commented on Chapter-1-initial-architecture/Src/Fitnet.IntegrationTests/Common/TestEngine/IntegrationEvents/Handlers/IntegrationEventHandlerScope.cs
> +internal sealed class IntegrationEventHandlerScope<TIntegrationEvent> : IDisposable where TIntegrationEvent : IIntegrationEvent
I had to add this class, because integration event handler has scoped dependency "OffersPersistance". I had to have way to access integration event handler. Now it is possible because of special scope.

2023-05-03 08:32 UTC, meaboutsoftware requested changes

2023-05-03 08:32 UTC, meaboutsoftware commented on Chapter-1-initial-architecture/Src/Fitnet.IntegrationTests/Common/TestEngine/IntegrationEvents/Handlers/IntegrationEventHandlerScope.cs
> +namespace SuperSimpleArchitecture.Fitnet.IntegrationTests.Common.TestEngine.IntegrationEvents.Handlers;
Too long lines :P (I know it would have been easier with static code analysis but let's leave this topic)

2023-05-03 08:32 UTC, meaboutsoftware commented on Chapter-1-initial-architecture/Src/Fitnet/Offers/Data/Database/OfferEntityConfiguration.cs
> +        builder.Property(offers => offers.PreparedAt).IsRequired();
What about other fields? Is there any not required?

2023-05-03 08:32 UTC, meaboutsoftware commented on Chapter-1-initial-architecture/Src/Fitnet/Offers/Data/Offer.cs
> +    private const decimal StandardDiscount = 0.1m;
Instead of having static discount on the offer, I would pass it inside your factory method PrepareStandardPassExtension. This way, when you add new method here e.g. PrepareGoldPassExtension, you pass the discount and you do not need to touch entity properties :) and so on

2023-05-03 17:34 UTC, kamilbaczek commented on Chapter-1-initial-architecture/Src/Fitnet.IntegrationTests/Common/TestEngine/IntegrationEvents/Handlers/IntegrationEventHandlerScope.cs
> +namespace SuperSimpleArchitecture.Fitnet.IntegrationTests.Common.TestEngine.IntegrationEvents.Handlers;
I have fixed style is this file. It is okay for you? :D

2023-05-03 17:46 UTC, kamilbaczek commented on Chapter-1-initial-architecture/Src/Fitnet/Offers/Data/Offer.cs
> +    private const decimal StandardDiscount = 0.1m;
I my opinion previous version was clean enough. We had private static property with exact discount for standard, and property with actual value of discount that is not static. I'm okey with your version as well. Now I have moved this value to factory method. It is better in your opinion now?

2023-05-03 18:11 UTC, kamilbaczek commented on Chapter-1-initial-architecture/Src/Fitnet/Offers/Data/Database/OfferEntityConfiguration.cs
> +        builder.Property(offers => offers.PreparedAt).IsRequired();
Fixed :D

2023-05-04 07:23 UTC, meaboutsoftware submitted a review, later dismissed
All is fine, good job! :)

2023-05-04 07:23 UTC, meaboutsoftware commented on Chapter-1-initial-architecture/Src/Fitnet/Offers/Data/Offer.cs
> +    private const decimal StandardDiscount = 0.1m;
yep :)

2023-05-04 18:13 UTC, closed without merging