Add platform and libraries documentation
meaboutsoftware/evolutionary-architecture pull request #45
Opened 2023-05-09 08:26 UTC by meaboutsoftware

This PR includes changes to root README related to filling out the Platforms and Libraries section:

- libraries and platforms used in production code
- libraries used in test code

2023-05-11 19:29 UTC, kamilbaczek commented on README.adoc
> +- https://github.com/fluentassertions/fluentassertions[FluentAssertions]
```suggestion
- https://github.com/fluentassertions/fluentassertions[FluentAssertions]
- https://dotnet.testcontainers.org[Testcontainers]
```

2023-05-12 09:55 UTC, kamilbaczek commented on README.adoc
> +## Libraries and Platforms Used
I think we should change ## to == like in other part of file. Are you okay?
@meaboutsoftware

2023-05-12 09:58 UTC, kamilbaczek requested changes
I think we should change ## to == like in other part of file. Are you okay?

2023-05-12 10:19 UTC, meaboutsoftware commented on README.adoc
> +## Libraries and Platforms Used
Done

2023-05-12 11:53 UTC, kamilbaczek approved these changes

2023-05-12 11:53 UTC, kamilbaczek approved these changes

2023-05-12 11:53 UTC, kamilbaczek approved these changes

2023-05-12 11:53 UTC, kamilbaczek approved these changes

2023-05-12 11:53 UTC, kamilbaczek approved these changes

2023-05-12 11:53 UTC, kamilbaczek approved these changes

2023-05-12 11:53 UTC, kamilbaczek approved these changes

2023-05-12 11:53 UTC, kamilbaczek approved these changes

2023-05-12 11:53 UTC, kamilbaczek approved these changes

2023-05-12 11:53 UTC, merged