Create empty projects for contracts module
meaboutsoftware/evolutionary-architecture pull request #52
Opened 2023-05-17 17:25 UTC by kamilbaczek

Pull Request includes:
- new empty projects for contracts module
- restructure virtual solution structure 
Pull Request not includes:
- reorganize physical dictionaries structure
- moved classes from directory to projects

2023-05-19 15:15 UTC, meaboutsoftware commented on Chapter-2-modules-separation/Src/Fitnet.sln
>  Global
I am missing Contracts.IntegrationTests and Contracts.Tests :)

2023-05-20 07:34 UTC, meaboutsoftware requested changes

2023-05-20 07:34 UTC, meaboutsoftware commented on Chapter-2-modules-separation/Src/Fitnet.Contracts.Api/Fitnet.Contracts.Api.csproj
> +        <TargetFramework>net7.0</TargetFramework>
Same as in my case, drop the TargetFramework (this node is created as default) :)

2023-05-20 07:49 UTC, kamilbaczek commented on Chapter-2-modules-separation/Src/Fitnet.Contracts.Api/Fitnet.Contracts.Api.csproj
> +        <TargetFramework>net7.0</TargetFramework>
Yep

2023-05-20 12:35 UTC, kamilbaczek commented on Chapter-2-modules-separation/Src/Fitnet.Contracts.Api/Class1.cs
> +﻿namespace EvolutionaryArchitecture.Fitnet.Contracts.Api;
Done

2023-05-20 12:35 UTC, kamilbaczek commented on Chapter-2-modules-separation/Src/Fitnet.sln
>  Global
I'm gonna add it in next PR.

2023-05-20 13:00 UTC, meaboutsoftware requested changes

2023-05-20 13:00 UTC, meaboutsoftware commented on Chapter-2-modules-separation/Src/Fitnet.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "Fitnet.Contracts.Application", "Fitnet.Contracts.Application\Fitnet.Contracts.Application.csproj", "{C7048CE6-7C8E-4C73-88A7-7119485ADFA8}"
Now you lost Infrastructure - it is not in solution:

![image](https://github.com/meaboutsoftware/evolutionary-architecture/assets/5842524/48b4d022-5ba8-4c16-b089-711a7a9cd0a5)

2023-05-20 13:08 UTC, kamilbaczek commented on Chapter-2-modules-separation/Src/Fitnet.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "Fitnet.Contracts.Application", "Fitnet.Contracts.Application\Fitnet.Contracts.Application.csproj", "{C7048CE6-7C8E-4C73-88A7-7119485ADFA8}"
you are right, sorry :D Fixed

2023-05-20 13:11 UTC, meaboutsoftware approved these changes

2023-05-20 13:18 UTC, merged