Story/contracts integration tests to dedicated project
meaboutsoftware/evolutionary-architecture pull request #64
Opened 2023-05-25 19:10 UTC by kamilbaczek

2023-05-26 10:39 UTC, meaboutsoftware requested changes

2023-05-26 10:39 UTC, meaboutsoftware commented on Chapter-2-modules-separation/Src/Fitnet.Common.IntegrationTests/Fitnet.Common.IntegrationTests.csproj
> +<Project Sdk="Microsoft.NET.Sdk.Web">
As this is not a test project but reusable project by tests, can we put it outside of Tests solution folder?

For me Tests solution folder should only contain Tests projects.

2023-05-26 10:39 UTC, meaboutsoftware commented on Chapter-2-modules-separation/Src/Fitnet.Common.IntegrationTests/Fitnet.Common.IntegrationTests.csproj
> +<Project Sdk="Microsoft.NET.Sdk.Web">
Instead of Web, reference Sdk

2023-05-26 10:39 UTC, meaboutsoftware commented on Chapter-2-modules-separation/Src/Fitnet.Common.IntegrationTests/Fitnet.Common.IntegrationTests.csproj
> +        <IsPackable>false</IsPackable>
As this is going to be a nuget package in the nearest future and this project will be referenced by other projects, it makes sense to make it packable (as fair as I remember, when you reference xunit in csproj, you must leave this setting set to true to make it packable, you cannot just remove it)

2023-05-26 14:26 UTC, kamilbaczek commented on Chapter-2-modules-separation/Src/Fitnet.Common.IntegrationTests/Fitnet.Common.IntegrationTests.csproj
> +<Project Sdk="Microsoft.NET.Sdk.Web">
Yep, you are right

2023-05-26 14:27 UTC, kamilbaczek commented on Chapter-2-modules-separation/Src/Fitnet.Common.IntegrationTests/Fitnet.Common.IntegrationTests.csproj
> +        <IsPackable>false</IsPackable>
Yes :D this should be packable

2023-05-27 07:27 UTC, meaboutsoftware approved these changes

2023-05-27 07:31 UTC, merged