Implement command query separation in contracts module
meaboutsoftware/evolutionary-architecture pull request #65
Opened 2023-05-29 05:24 UTC by kamilbaczek

2023-05-30 06:21 UTC, meaboutsoftware requested changes
Nice one!

2023-05-30 06:21 UTC, meaboutsoftware commented on Chapter-2-modules-separation/Docs/ArchitectureDecisionLog/0014-applying-command-query-separation-to-contracts-module.adoc
> +== Context
Problem (we have it in 11 adocs - I will change it in 0012 and 0013)

2023-05-30 06:21 UTC, meaboutsoftware commented on Chapter-2-modules-separation/Src/Fitnet.Contracts.Api/Prepare/PrepareContractRequest.cs
> +public sealed record PrepareContractRequest(int CustomerAge, int CustomerHeight, DateTimeOffset PreparedAt)
As of today it can be internal

2023-05-30 06:21 UTC, meaboutsoftware commented on Chapter-2-modules-separation/Src/Fitnet.Contracts.Api/Sign/SignContractRequest.cs
> +public sealed record SignContractRequest(DateTimeOffset SignedAt)
Same here - can be internal

2023-05-30 06:21 UTC, meaboutsoftware commented on Chapter-2-modules-separation/Src/Fitnet.Contracts.Application/Commands/Sign/SignContractCommandHandler.cs
> +        _contractsRepository = contractsRepository;
Add spacing between lines 11 and 12

2023-05-30 06:21 UTC, meaboutsoftware commented on Chapter-2-modules-separation/Src/Fitnet.Contracts.Infrastructure/Database/Repositories/ContractsRepository.cs
> +    {
It would be great to check if contract exists. If yes, throw an exception

2023-05-30 14:30 UTC, kamilbaczek commented on Chapter-2-modules-separation/Docs/ArchitectureDecisionLog/0014-applying-command-query-separation-to-contracts-module.adoc
> +== Context
Done

2023-05-30 14:31 UTC, kamilbaczek commented on Chapter-2-modules-separation/Src/Fitnet.Contracts.Api/Sign/SignContractRequest.cs
> +public sealed record SignContractRequest(DateTimeOffset SignedAt)
Done

2023-05-30 14:31 UTC, kamilbaczek commented on Chapter-2-modules-separation/Src/Fitnet.Contracts.Api/Prepare/PrepareContractRequest.cs
> +public sealed record PrepareContractRequest(int CustomerAge, int CustomerHeight, DateTimeOffset PreparedAt)
Done

2023-05-30 14:31 UTC, kamilbaczek commented on Chapter-2-modules-separation/Src/Fitnet.Contracts.Application/Commands/Sign/SignContractCommandHandler.cs
> +        _contractsRepository = contractsRepository;
Done :D

2023-05-30 14:32 UTC, kamilbaczek commented on Chapter-2-modules-separation/Src/Fitnet.Contracts.Infrastructure/Database/Repositories/ContractsRepository.cs
> +    {
In chapter one we have not this validation :D We can add in two placed but in another Pull Request. It is okay for you?

2023-05-30 17:12 UTC, meaboutsoftware commented on Chapter-2-modules-separation/Src/Fitnet.Contracts.Infrastructure/Database/Repositories/ContractsRepository.cs
> +    {
Ok, you can then change it only here and then create another PR (this is one of things that were forgotten, we have several other ones)

2023-05-31 09:47 UTC, meaboutsoftware approved these changes

2023-05-31 10:22 UTC, merged