Check if contract exists
meaboutsoftware/evolutionary-architecture pull request #70
Opened 2023-06-04 09:13 UTC by kamilbaczek

2023-06-05 06:26 UTC, meaboutsoftware requested changes

2023-06-05 06:26 UTC, meaboutsoftware commented on Chapter-2-modules-separation/Src/Fitnet.Contracts.Application/Commands/Prepare/PreapreContractCommand.cs
>  namespace EvolutionaryArchitecture.Fitnet.Contracts.Application.Commands.Prepare;
Adjust name of the file. It is Preapre instead of Prepare :)

2023-06-05 06:26 UTC, meaboutsoftware commented on Chapter-2-modules-separation/Src/Fitnet.Contracts.Application/Commands/Prepare/PrepareContractCommandHandler.cs
>  namespace EvolutionaryArchitecture.Fitnet.Contracts.Application.Commands.Prepare;
Can you please remove folder Commands? Instead just have:

Fitnet.Contract.Application.Prepare :)

This way we do not have technicalities in our soultion structure and it is extremely easy to read entire process:

1. In Api you see folder Prepare
2. In Application you see folder Prepare
3. In Core you see folder Prepare
4. In tests you see folder Prepare

Now if you e.g. want to recognize or drop this process, it will take you a minute or two instead of 15

2023-06-05 06:26 UTC, meaboutsoftware commented on Chapter-2-modules-separation/Src/Fitnet.Contracts.Application/Commands/Prepare/PrepareContractCommandHandler.cs
> +        await EnsureThatCustomerHasNoUnsignedContract(command.CustomerId, cancellationToken);
Business logic leak to application :)

In Application it should only steer the flow. Example? Check if entity exists or not. If yes, continue, if not throw. Here you have something more because you check if there is unsigned contract (business logic because of this _unsigned_ as you can have at least 2 states - signed and unsigned).

How to deal with that? Easy -> pass boolean to Contract.Prepare, add business rule and include this check in Core (do not forget about unit tests ;))

2023-06-05 18:12 UTC, kamilbaczek commented on Chapter-2-modules-separation/Src/Fitnet.Contracts.Application/Commands/Prepare/PreapreContractCommand.cs
>  namespace EvolutionaryArchitecture.Fitnet.Contracts.Application.Commands.Prepare;
Fixed

2023-06-05 18:13 UTC, kamilbaczek commented on Chapter-2-modules-separation/Src/Fitnet.Contracts.Application/Commands/Prepare/PrepareContractCommandHandler.cs
> +        await EnsureThatCustomerHasNoUnsignedContract(command.CustomerId, cancellationToken);
I like this idea a lot. In result domain layer we have all business rules :D

2023-06-06 07:40 UTC, meaboutsoftware commented on Chapter-2-modules-separation/Src/Fitnet.Contracts.Application/Commands/Prepare/PrepareContractCommandHandler.cs
>  namespace EvolutionaryArchitecture.Fitnet.Contracts.Application.Commands.Prepare;
What about this one? :)

2023-06-06 07:52 UTC, meaboutsoftware requested changes

2023-06-06 07:52 UTC, meaboutsoftware commented on Chapter-2-modules-separation/Src/Fitnet.Contracts.Application/Commands/Preapre/PreapreContractCommand.cs
> +namespace EvolutionaryArchitecture.Fitnet.Contracts.Application.Commands.Preapre;
You have here preapre instead of prepare (as well in the file name)

2023-06-06 07:52 UTC, meaboutsoftware commented on Chapter-2-modules-separation/Src/Fitnet.Contracts.Application/Commands/Preapre/PrepareContractCommandHandler.cs
> +        var previousContract = await _contractsRepository.GetPreviousForCustomerAsync(command.CustomerId, cancellationToken);
Just grab the contract (using your GetPreviousForCustomerAsync) and throw exception here if not existing. Exactly as you have here:

```
public async Task Handle(SignContractCommand command, CancellationToken cancellationToken)
    {
        var contract = await _contractsRepository.GetByIdAsync(command.Id, cancellationToken);
        if (contract is null)
           throw new ResourceNotFoundException(command.Id);
        
        contract.Sign(command.SignedAt);
        await _contractsRepository.CommitAsync(cancellationToken);
    }
```

This way you will also simplify the contract of Contract.Prepare method where as the last parameter you will either have false or true (bool isPreviousContractSigned instead of bool? isPreviousContractSigned = null)

and you will simplify business rule check as it does not need to check for null

2023-06-06 18:43 UTC, kamilbaczek commented on Chapter-2-modules-separation/Src/Fitnet.Contracts.Application/Commands/Preapre/PrepareContractCommandHandler.cs
> +        var previousContract = await _contractsRepository.GetPreviousForCustomerAsync(command.CustomerId, cancellationToken);
"Just grab the contract (using your GetPreviousForCustomerAsync) and throw exception here if not existing." I don't understand if previous contract no exits and for e.g this is first contract for particular customer and we will throw exception first contract will never be created.

Is my understanding right?

2023-06-06 18:44 UTC, kamilbaczek commented on Chapter-2-modules-separation/Src/Fitnet.Contracts.Core/PrepareContract/BusinessRules/PreviousContractHasToBeSignedRule.cs
> +namespace EvolutionaryArchitecture.Fitnet.Contracts.Core.PrepareContract.BusinessRules;
Let me change in next PR I won't mix refactor with feature code.

2023-06-06 20:38 UTC, meaboutsoftware commented on Chapter-2-modules-separation/Src/Fitnet.Contracts.Application/Commands/Preapre/PrepareContractCommandHandler.cs
> +        var previousContract = await _contractsRepository.GetPreviousForCustomerAsync(command.CustomerId, cancellationToken);
Yes, I made a mistake here. You are correct

2023-06-07 06:24 UTC, meaboutsoftware approved these changes

2023-06-07 07:13 UTC, merged