Move configuration of connection strings to modules itself
meaboutsoftware/evolutionary-architecture pull request #75
Opened 2023-06-11 11:31 UTC by meaboutsoftware

2023-06-12 18:06 UTC, kamilbaczek requested changes

2023-06-12 18:06 UTC, kamilbaczek commented on Chapter-2-modules-separation/Src/Fitnet/Modules.cs
> +public enum Modules
I would rather use record instead enum here, because we don't have to use toString everywhere where we would like to use it.
<img width="606" alt="image" src="https://github.com/meaboutsoftware/evolutionary-architecture/assets/74410956/ed2fe340-12cc-478e-9ad5-a5fa1bb3fb6a">
internal record Module(string Value)
{
    internal static readonly Module Contracts = new("Contracts");
    internal static readonly Module Reports = new("Reports");
    
    public static implicit operator string(Module module) => module.Value;
}

<img width="615" alt="image" src="https://github.com/meaboutsoftware/evolutionary-architecture/assets/74410956/76423c40-cacd-4b38-9387-5e6a16fa12b8">

what you think?

2023-06-12 18:06 UTC, kamilbaczek commented on Chapter-2-modules-separation/Src/Fitnet/Program.cs
> +builder.Services.AddFeatureManagement();
We have used new library here it will be nice to mention it on our libraries list in Readme.

2023-06-13 06:34 UTC, meaboutsoftware commented on Chapter-2-modules-separation/Src/Fitnet.Offers.IntegrationTests/OffersDatabaseConfiguration.cs
> +internal class OffersDatabaseConfiguration : IDatabaseConfiguration
Done

2023-06-13 06:34 UTC, meaboutsoftware commented on Chapter-2-modules-separation/Src/Fitnet.Common.Infrastructure/Modules/ModuleAvailabilityValidator.cs
> +public static class ModuleAvailabilityValidator
I changed it to Checker

2023-06-13 06:37 UTC, meaboutsoftware commented on Chapter-2-modules-separation/Src/Fitnet.Offers.IntegrationTests/OffersDatabaseConfiguration.cs
> +    {
Done

2023-06-13 06:37 UTC, meaboutsoftware commented on Chapter-2-modules-separation/Src/Fitnet/Modules.cs
> +public enum Modules
Why not :)

2023-06-13 06:40 UTC, meaboutsoftware commented on Chapter-2-modules-separation/Src/Fitnet/Program.cs
> +builder.Services.AddFeatureManagement();
Good point! Done

2023-06-13 08:19 UTC, kamilbaczek approved these changes

2023-06-13 08:23 UTC, merged