Rearrange register pass process to pass be registered after contract is signed
meaboutsoftware/evolutionary-architecture pull request #80
Opened 2023-06-17 16:06 UTC by kamilbaczek

- removed endpoint
- created event handler
- modified tests
- add contract validity properties for event

2023-06-17 16:09 UTC, kamilbaczek commented on Chapter-1-initial-architecture/Src/Fitnet/Contracts/SignContract/Events/ContractSignedEvent.cs
> +    internal static ContractSignedEvent Create(Guid contractId, Guid contractCustomerId, DateTimeOffset validityFrom, DateTimeOffset validityTo) =>
To have possibility manipulate dates of pass I had to introduce validity dates for contract and based on that pass dates are initialized. Otherwise it was hard to manipulate dates for e.g in Reports Tests. What you think about that?

2023-06-17 16:12 UTC, kamilbaczek commented on Chapter-1-initial-architecture/Src/Fitnet.IntegrationTests/Passes/MarkPassAsExpired/MarkPassAsExpiredTests.cs
> +    [Fact(Skip = "Register pass as event cannot return pass id. Get all pass query should be created and used here to make this test pass.")]
Before endpoint returned id I a was able to get pass that I can expire. Now this is done asynchronously and I can't get it. I prefer create get all pass query that I could use here to get pass that I created. I could do it in next MR

2023-06-19 18:32 UTC, meaboutsoftware commented on Chapter-1-initial-architecture/Src/Fitnet/Contracts/Data/Contract.cs
> +    internal static Contract PrepareStandard(Guid customerId, int customerAge, int customerHeight, DateTimeOffset preparedAt, bool? isPreviousContractSigned = null)
I would just call it Prepare and Duration. This way we do not confuse someone - when e.g. new duration comes in, then we can name it Standard, Premium etc. What do you think?

2023-06-19 18:32 UTC, meaboutsoftware commented on Chapter-1-initial-architecture/Src/Fitnet/Passes/GetAllPasses/GetAllEndpoint.cs
> +internal static class GetAllEndpoint
To stick with convention, GetAllPassesEndpoint

2023-06-19 18:46 UTC, kamilbaczek commented on Chapter-1-initial-architecture/Src/Fitnet/Passes/GetAllPasses/GetAllEndpoint.cs
> +internal static class GetAllEndpoint
fixed

2023-06-19 18:46 UTC, kamilbaczek commented on Chapter-1-initial-architecture/Src/Fitnet/Contracts/Data/Contract.cs
> +    internal static Contract PrepareStandard(Guid customerId, int customerAge, int customerHeight, DateTimeOffset preparedAt, bool? isPreviousContractSigned = null)
We can do it

2023-06-19 19:31 UTC, kamilbaczek commented on Chapter-1-initial-architecture/Src/Fitnet/Contracts/Data/Contract.cs
> +    internal static Contract PrepareStandard(Guid customerId, int customerAge, int customerHeight, DateTimeOffset preparedAt, bool? isPreviousContractSigned = null)
Duration property already exists. Can we stay with Standard Duration but change only prepare?

2023-06-20 18:13 UTC, meaboutsoftware requested changes
Very good job!

2023-06-20 18:13 UTC, meaboutsoftware commented on Chapter-1-initial-architecture/Src/Fitnet.IntegrationTests/Passes/MarkPassAsExpired/MarkPassAsExpiredTests.cs
>  using Fitnet.Shared.Events;
Not used

2023-06-20 18:13 UTC, meaboutsoftware commented on Chapter-1-initial-architecture/Src/Fitnet.IntegrationTests/Passes/MarkPassAsExpired/MarkPassAsExpiredTests.cs
>  using EvolutionaryArchitecture.Fitnet.Passes.RegisterPass;
Not used

2023-06-20 18:13 UTC, meaboutsoftware commented on Chapter-1-initial-architecture/Src/Fitnet.IntegrationTests/Passes/RegisterPass/ContractSignedEventFaker.cs
> +    private ContractSignedEventFaker(DateTimeOffset? validityFrom, DateTimeOffset? validityTo)
Can you call it signedAt/expiringAt?

2023-06-20 18:13 UTC, meaboutsoftware commented on Chapter-1-initial-architecture/Src/Fitnet.IntegrationTests/Reports/GenerateNewPassesPerMonthReport/GenerateNewPassesPerMonthReportTests.cs
>  using Fitnet.Passes;
Remove unused usings (all in this file)

2023-06-20 18:13 UTC, meaboutsoftware commented on Chapter-1-initial-architecture/Src/Fitnet/Contracts/Data/Contract.cs
> +    private static TimeSpan StandardDuration => TimeSpan.FromDays(365);
I would call it just Duration (when adding new type, then it makes sense to distinguish it but to reduce cognitive complexity it makes sense to simplify it as much as possible :)

2023-06-20 19:05 UTC, kamilbaczek commented on Chapter-1-initial-architecture/Src/Fitnet/Contracts/Data/Contract.cs
> +    private static TimeSpan StandardDuration => TimeSpan.FromDays(365);
there is  public TimeSpan Duration { get; init; }  in this class that persist duration. Standard duration it is a static value. What you suggest to change I that case?

2023-06-20 19:41 UTC, meaboutsoftware commented on Chapter-1-initial-architecture/Src/Fitnet/Contracts/Data/Contract.cs
> +    private static TimeSpan StandardDuration => TimeSpan.FromDays(365);
Ok, let's leave it

2023-06-20 19:42 UTC, meaboutsoftware approved these changes

2023-06-20 19:43 UTC, merged