Chapter 2 make register pass as event handler
meaboutsoftware/evolutionary-architecture pull request #81
Opened 2023-06-25 09:23 UTC by kamilbaczek

2023-06-25 09:24 UTC, kamilbaczek commented on Chapter-2-modules-separation/Src/Fitnet.Contracts.Application/Fitnet.Contracts.Application.csproj
> +    <ProjectReference Include="..\Fitnet.Common.Infrastructure\Fitnet.Common.Infrastructure.csproj" />
This is something that I would like to discuss because we are using Common infrastructure in application layer that is not best because encourage developers to mix infra and core Layer. I would like to rearrange this somehow but not in this MR

2023-06-29 17:04 UTC, meaboutsoftware requested changes

2023-06-29 17:04 UTC, meaboutsoftware commented on Chapter-2-modules-separation/Src/Fitnet.Contracts.Application/Sign/ContractSignedEvent.cs
> +public record ContractSignedEvent(Guid Id, Guid ContractId, Guid ContractCustomerId, DateTimeOffset SignedAt, DateTimeOffset ExpireAt, DateTimeOffset OccurredDateTime) : IIntegrationEvent
It is an integration event - as agreed and done in Passes module, it should be in Fitnet.Contracts.IntegrationEvents project

2023-06-29 17:04 UTC, meaboutsoftware commented on Chapter-2-modules-separation/Src/Fitnet.Contracts.Application/Sign/SignContractCommandHandler.cs
> +        contract.Sign(command.SignedAt, _systemClock);
Do not bother core (business logic with system clock that is some kind of mechanism. You do instead:

```
var expiringAt = _systemClock.Now.Add(contract.Duration);

contract.Sign(command.SignedAt, expiringAt)
```

2023-06-30 05:53 UTC, kamilbaczek commented on Chapter-2-modules-separation/Src/Fitnet.Contracts.Application/Sign/SignContractCommandHandler.cs
> +        contract.Sign(command.SignedAt, _systemClock);
Calculating expiringAt outside the contract domain model violates encapsulation by exposing implementation details to the calling code. Always we caller want to use sign method needs to know how calculate contract expiration data.

```suggestion
        contract.Sign(command.SignedAt, _systemClock.Now);
```

To increase domain purity we can pass now date as parameter to method and still has logic encapsulated. What you think?

2023-06-30 05:54 UTC, kamilbaczek commented on Chapter-2-modules-separation/Src/Fitnet.Contracts.Application/Sign/ContractSignedEvent.cs
> +public record ContractSignedEvent(Guid Id, Guid ContractId, Guid ContractCustomerId, DateTimeOffset SignedAt, DateTimeOffset ExpireAt, DateTimeOffset OccurredDateTime) : IIntegrationEvent
Yeah I forgot about this in chapter 2. I will fix it.

2023-06-30 06:37 UTC, meaboutsoftware commented on Chapter-2-modules-separation/Src/Fitnet.Contracts.Application/Sign/SignContractCommandHandler.cs
> +        contract.Sign(command.SignedAt, _systemClock);
That's fine, I like it!

2023-07-01 07:16 UTC, kamilbaczek commented on Chapter-2-modules-separation/Src/Fitnet.Contracts.Application/Sign/SignContractCommandHandler.cs
> +        contract.Sign(command.SignedAt, _systemClock);
Fixed 👌

2023-07-01 07:59 UTC, meaboutsoftware requested changes

2023-07-01 07:59 UTC, meaboutsoftware commented on Chapter-2-modules-separation/Src/Fitnet.Contracts.IntegrationEvents/Fitnet.Contracts.IntegrationEvents.csproj
> +    <PropertyGroup>
Not needed property group

2023-07-01 08:02 UTC, kamilbaczek commented on Chapter-2-modules-separation/Src/Fitnet.Contracts.IntegrationEvents/Fitnet.Contracts.IntegrationEvents.csproj
> +    <PropertyGroup>
removed

2023-07-01 08:03 UTC, meaboutsoftware approved these changes

2023-07-01 08:04 UTC, merged