First step to Microservices move queue
meaboutsoftware/evolutionary-architecture pull request #99
Opened 2023-07-15 16:31 UTC by kamilbaczek

2023-07-20 16:59 UTC, kamilbaczek commented on Chapter-3-microservice-extraction/Src/Fitnet.Common.Infrastructure/Events/EventBus/External/ExternalEventBusModule.cs
> +            rabbitMqHostConfigurator.Username(configuration["RabbitMq:Username"]);
In next MR I will extract this config to Options class

2023-07-20 18:34 UTC, kamilbaczek commented on Chapter-3-microservice-extraction/Docs/ArchitectureDecisionLog/0017-extraction-contracts-module.adoc
> +* _Resource Optimization_: A dedicated team for contracts can manage their service and independently deploy frequent updates.
Not good category

2023-07-22 18:33 UTC, kamilbaczek commented on Chapter-3-microservice-extraction/Docs/ArchitectureDecisionLog/0017-extraction-contracts-module.adoc
> +Positive consequences of this decision include:
remove this sentence

2023-07-22 19:10 UTC, kamilbaczek commented on Chapter-3-microservice-extraction/Src/Fitnet/Program.cs
> +builder.Services.AddFeatureManagement();
common infrastructure has to have registration all consumer in modules that why is below, but feature management has to have be registered before modules bucease that have to check enability

2023-07-22 19:11 UTC, kamilbaczek commented on Chapter-3-microservice-extraction/Src/Fitnet/Program.cs
> +builder.Services.AddFeatureManagement();
If you have idea how to reorganize it better, please writedown.

2023-07-22 19:11 UTC, kamilbaczek commented on Chapter-3-microservice-extraction/Src/Fitnet/Program.cs
> +builder.Services.AddFeatureManagement();
I assumed it is good enough for now.

2023-07-23 07:44 UTC, meaboutsoftware requested changes
You did a really great job here! :)

2023-07-23 07:44 UTC, meaboutsoftware commented on Chapter-3-microservice-extraction/Docs/ArchitectureDecisionLog/0017-extraction-contracts-module.adoc
> += ADR 17: Extraction of Contract Module as a Separate Microservice
Remove ADR 17 and stay with the current convention of:

17. Extraction of..

Same in other adrs :)

2023-07-23 07:44 UTC, meaboutsoftware commented on Chapter-3-microservice-extraction/Docs/ArchitectureDecisionLog/0017-extraction-contracts-module.adoc
> +
Date is missing

2023-07-23 07:44 UTC, meaboutsoftware commented on Chapter-3-microservice-extraction/Docs/ArchitectureDecisionLog/0018-adopt-out-of-process-message-queue.adoc
> +
Date is missing

2023-07-23 07:44 UTC, meaboutsoftware commented on Chapter-3-microservice-extraction/Src/Fitnet.Common.Infrastructure/CommonInfrastructureModule.cs
>  using EvolutionaryArchitecture.Fitnet.Common.Infrastructure.Events.EventBus;
You can move 2 usings to namespace

2023-07-23 07:44 UTC, meaboutsoftware commented on Chapter-3-microservice-extraction/Src/Fitnet.Common.Infrastructure/Events/EventBus/External/Consumers/ConsumerConfiguration.cs
> +    public static ConsumerConfiguration Configure(string queueName, Type consumerType) =>
Why not internal? Same with properties

2023-07-23 07:44 UTC, meaboutsoftware commented on Chapter-3-microservice-extraction/Src/Fitnet.Common.Infrastructure/Events/EventBus/External/ExternalEventBusModule.cs
> +    private static void RegisterConsumers(IEnumerable<ConsumerConfiguration> endpoints, IBusRegistrationConfigurator configurator)
You can use IRegistrationConfigurator instead of IBusRegistrationConfigurator

2023-07-23 07:44 UTC, meaboutsoftware commented on Chapter-3-microservice-extraction/Src/Fitnet.Common.Infrastructure/Events/EventBus/InMemory/IInMemoryEventBus.cs
> +public interface IInMemoryEventBus : IEventBus
Better naming would be IInternalEventBus but anyway it will be changed in one of the next branches :)

2023-07-23 07:44 UTC, meaboutsoftware commented on Chapter-3-microservice-extraction/Src/Fitnet/Program.cs
> +builder.Services.AddFeatureManagement();
It is fine for now, absolutely

2023-07-23 07:44 UTC, meaboutsoftware commented on Chapter-3-microservice-extraction/docker-compose.yml
> +    rabbitmq:
Please fix indentation - rabbitmq should be on the same level as postgres

2023-07-23 08:47 UTC, kamilbaczek commented on Chapter-3-microservice-extraction/Src/Fitnet.Common.Infrastructure/Events/EventBus/InMemory/IInMemoryEventBus.cs
> +public interface IInMemoryEventBus : IEventBus
Yeah we plan to get rid of InMemoryService Bus but you are right

Should be InMemory and OutOfProcess EventBus bus or
Internal and External

But like you said we will keep current version until we will not remove InMemory

2023-07-23 09:23 UTC, meaboutsoftware approved these changes

2023-07-23 10:09 UTC, merged